# Build settings
markdown: redcarpet
highlighter: pygments
permalink : /:title/

title: "90 days in the US"
name: 'Mathias Lynnerup Jakobsen'
description: >
    Nu sker det endeligt! Vi tager 3 måneder til USA. Her skal vi køre 22.000 km. fra New York til San Fransico, og tilbage igen. Her på siden kan i følge lidt med i, hvor vi er og hvad vi går og laver.
states: 0


cover: "/assets/images/map.png"
logo: "/assets/images/logo.png"
paginate:	5

url: "http://90daysinthe.us"
baseurl: ""
mapbox_token: "pk.eyJ1IjoibWF0aGlhc2pha29ic2VuIiwiYSI6InV6eFNWcjAifQ.FxCifm3JCCSz9WhKHUlv4g"
