# Build settings
markdown: redcarpet
highlighter: pygments
permalink : /:title/

title: "Mathias og Line"
name: 'Mathias Lynnerup Jakobsen'
description: >
   A Jekyll theme - Medium inspired



cover: "/assets/images/map.png"
logo: "/assets/images/logo.png"
paginate:	5

url: "http://muri.ca"
baseurl: ""
mapbox_token: "pk.eyJ1IjoibWF0aGlhc2pha29ic2VuIiwiYSI6InV6eFNWcjAifQ.FxCifm3JCCSz9WhKHUlv4g"


social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
